name: Run Hayabusa Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      thor-branch:
        description: 'Branch to test against'
        required: true
        default: 'release/hayabusa'
  workflow_call:
    inputs:
      thor-branch:
        type: string
        required: false
      codebuild-name:
        type: string
        required: false
        default: codebuild-Hayabusa-E2E


concurrency:
  cancel-in-progress: true
  group: run-e2e-${{ github.run_id }}-${{ github.run_attempt }}

permissions:
  contents: read

jobs:
  run-tests:
    runs-on:
      - ${{ inputs.codebuild-name || 'codebuild-Hayabusa-E2E' }}-${{ github.run_id }}-${{ github.run_attempt }}
      - image:arm-3.0
      - instance-size:large # xlarge=32 vCPUs, 64 GiB memory, large=8 vCPUs, 16 GiB memory

    strategy:
      matrix:
        packages:
          - tests/validations
          - tests/delegations
          - tests/slots
          - tests/energy
          - tests/stargate
          - tests/forks
      fail-fast: false

    steps:
      - name: Checkout E2E
        uses: actions/checkout@v4
        with:
          repository: vechain/hayabusa-e2e
          path: hayabusa-e2e

      - name: Checkout Thor
        uses: actions/checkout@v4
        with:
          repository: vechain/thor
          path: thor
          ref: ${{ inputs.thor-branch || 'release/hayabusa' }}

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Test
        run: go test -v -failfast -timeout 3600s ./${{ matrix.packages }}
        working-directory: ${{ github.workspace }}/hayabusa-e2e
        env:
          THOR_WORKING_DIR: ${{ github.workspace }}/thor
